from modCustomSet import *
set1 = CustomSet([1,3,5,3])
set2 = CustomSet([10,30,20])
set3 = CustomSet([1,3,2,4])
set4 = CustomSet([1,2])
set5 = CustomSet([1,3,1])
set6 = CustomSet([1,2,3,4,4])
print("Testing Union")
print(set1.or_(set2))
print(set2.or_(set3))
print(set3.or_(set4))
print(set4.or_(set5))
print("Testing Intersection")
print(set1.and_(set2))
print(set1.and_(set3))
print(set3.and_(set4))
print(set4.and_(set5))
print("Testing Difference")
print(set1.__sub__(set3))
print(set3.__sub__(set1))
print(set4.__sub__(set5))
print(set6.__sub__(set5))
print("Testing Membership")
print(set1.__contains__(5))
print(set2.__contains__(15))
print(set6.__contains__(3))
print(set4.__contains__(2))
print("Testing Subset")
print(set5.__le__(set6))
print(set6.__le__(set5))
print(set1.__le__(set2))
print(set2.__le__(set1))
print("Testing Superset")
print(set5.__ge__(set6))
print(set6.__ge__(set5))
print(set4.__ge__(set3))
print(set3.__ge__(set4))
print("Testing Length")
print(set6.__len__())
print(set1.__len__())
print(set4.__len__())
print(set2.__len__())
print("Testing Convert")
print(set2.__str__())
print(set3.__str__())
print(set1.__str__())
print(set4.__str__())
