from modCustomSet import *
set1 = CustomSet([1,3,5,3])
set2 = CustomSet([10,30,20])
set3 = CustomSet([1,3,2,4])
set4 = CustomSet([1,2])
set5 = CustomSet([1,3,1])
set6 = CustomSet([1,2,3,4,4])
print("Testing Union")
print(set1.union(set2))
print(set2.union(set3))
print(set3.union(set4))
print(set4.union(set5))
print("Testing Intersection")
print(set1.intersection(set2))
print(set1.intersection(set3))
print(set3.intersection(set4))
print(set4.intersection(set5))
print("Testing Difference")
print(set1.differenceMethod(set3))
print(set3.differenceMethod(set1))
print(set4.differenceMethod(set5))
print(set6.differenceMethod(set5))
print("Testing Membership")
print(set1.membership(5))
print(set2.membership(15))
print(set6.membership(3))
print(set4.membership(2))
print("Testing Subset")
print(set5.__le__(set6))
print(set6.__le__(set5))
print(set1.__le__(set2))
print(set2.__le__(set1))
print("Testing Superset")
print(set5.__ge__(set6))
print(set6.__ge__(set5))
print(set4.__ge__(set3))
print(set3.__ge__(set4))
print("Testing Length")
print(set6.lengthMethod())
print(set1.lengthMethod())
print(set4.lengthMethod())
print(set2.lengthMethod())
print("Testing Convert")
print(set2.curlyBracesMethod())
print(set3.curlyBracesMethod())
print(set1.curlyBracesMethod())
print(set4.curlyBracesMethod())
